// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: newproto/fruitcart.proto

package go_fruit_cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserCredential) Reset() {
	*x = UserCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredential) ProtoMessage() {}

func (x *UserCredential) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredential.ProtoReflect.Descriptor instead.
func (*UserCredential) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{0}
}

func (x *UserCredential) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firsname string `protobuf:"bytes,1,opt,name=firsname,proto3" json:"firsname,omitempty"`
	Lastname string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Cartid   string `protobuf:"bytes,4,opt,name=cartid,proto3" json:"cartid,omitempty"`
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetails) GetFirsname() string {
	if x != nil {
		return x.Firsname
	}
	return ""
}

func (x *UserDetails) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UserDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetails) GetCartid() string {
	if x != nil {
		return x.Cartid
	}
	return ""
}

type ProductCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid string `protobuf:"bytes,1,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *ProductCredential) Reset() {
	*x = ProductCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCredential) ProtoMessage() {}

func (x *ProductCredential) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCredential.ProtoReflect.Descriptor instead.
func (*ProductCredential) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{2}
}

func (x *ProductCredential) GetProductid() string {
	if x != nil {
		return x.Productid
	}
	return ""
}

type ProductDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productname        string  `protobuf:"bytes,1,opt,name=productname,proto3" json:"productname,omitempty"`
	Productdescription string  `protobuf:"bytes,2,opt,name=productdescription,proto3" json:"productdescription,omitempty"`
	Productamount      float64 `protobuf:"fixed64,3,opt,name=productamount,proto3" json:"productamount,omitempty"`
	Productimage       string  `protobuf:"bytes,4,opt,name=productimage,proto3" json:"productimage,omitempty"`
}

func (x *ProductDetails) Reset() {
	*x = ProductDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetails) ProtoMessage() {}

func (x *ProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetails.ProtoReflect.Descriptor instead.
func (*ProductDetails) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{3}
}

func (x *ProductDetails) GetProductname() string {
	if x != nil {
		return x.Productname
	}
	return ""
}

func (x *ProductDetails) GetProductdescription() string {
	if x != nil {
		return x.Productdescription
	}
	return ""
}

func (x *ProductDetails) GetProductamount() float64 {
	if x != nil {
		return x.Productamount
	}
	return 0
}

func (x *ProductDetails) GetProductimage() string {
	if x != nil {
		return x.Productimage
	}
	return ""
}

type TotalCartAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Totalamount int64 `protobuf:"varint,1,opt,name=totalamount,proto3" json:"totalamount,omitempty"`
}

func (x *TotalCartAmount) Reset() {
	*x = TotalCartAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalCartAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalCartAmount) ProtoMessage() {}

func (x *TotalCartAmount) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalCartAmount.ProtoReflect.Descriptor instead.
func (*TotalCartAmount) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{4}
}

func (x *TotalCartAmount) GetTotalamount() int64 {
	if x != nil {
		return x.Totalamount
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{5}
}

type AllUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserDetails `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *AllUsers) Reset() {
	*x = AllUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newproto_fruitcart_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUsers) ProtoMessage() {}

func (x *AllUsers) ProtoReflect() protoreflect.Message {
	mi := &file_newproto_fruitcart_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUsers.ProtoReflect.Descriptor instead.
func (*AllUsers) Descriptor() ([]byte, []int) {
	return file_newproto_fruitcart_proto_rawDescGZIP(), []int{6}
}

func (x *AllUsers) GetUsers() []*UserDetails {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_newproto_fruitcart_proto protoreflect.FileDescriptor

var file_newproto_fruitcart_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x65, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x75, 0x69, 0x74,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x73, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x72, 0x74, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x0f, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x61, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0xd1, 0x01, 0x0a, 0x1a, 0x46, 0x72, 0x75, 0x69,
	0x74, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x1a, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x31, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x1a, 0x0f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x37, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x61, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x1a, 0x10, 0x2e, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x61, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x09, 0x2e, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x2f,
	0x67, 0x6f, 0x2d, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2d, 0x63, 0x61, 0x72, 0x74, 0x3b, 0x67, 0x6f,
	0x5f, 0x66, 0x72, 0x75, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_newproto_fruitcart_proto_rawDescOnce sync.Once
	file_newproto_fruitcart_proto_rawDescData = file_newproto_fruitcart_proto_rawDesc
)

func file_newproto_fruitcart_proto_rawDescGZIP() []byte {
	file_newproto_fruitcart_proto_rawDescOnce.Do(func() {
		file_newproto_fruitcart_proto_rawDescData = protoimpl.X.CompressGZIP(file_newproto_fruitcart_proto_rawDescData)
	})
	return file_newproto_fruitcart_proto_rawDescData
}

var file_newproto_fruitcart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_newproto_fruitcart_proto_goTypes = []interface{}{
	(*UserCredential)(nil),    // 0: UserCredential
	(*UserDetails)(nil),       // 1: UserDetails
	(*ProductCredential)(nil), // 2: ProductCredential
	(*ProductDetails)(nil),    // 3: ProductDetails
	(*TotalCartAmount)(nil),   // 4: TotalCartAmount
	(*Empty)(nil),             // 5: Empty
	(*AllUsers)(nil),          // 6: AllUsers
}
var file_newproto_fruitcart_proto_depIdxs = []int32{
	1, // 0: AllUsers.users:type_name -> UserDetails
	0, // 1: FruitCartManagementService.GetUser:input_type -> UserCredential
	2, // 2: FruitCartManagementService.GetProduct:input_type -> ProductCredential
	0, // 3: FruitCartManagementService.GetTotalCartAmount:input_type -> UserCredential
	5, // 4: FruitCartManagementService.GetUsers:input_type -> Empty
	1, // 5: FruitCartManagementService.GetUser:output_type -> UserDetails
	3, // 6: FruitCartManagementService.GetProduct:output_type -> ProductDetails
	4, // 7: FruitCartManagementService.GetTotalCartAmount:output_type -> TotalCartAmount
	6, // 8: FruitCartManagementService.GetUsers:output_type -> AllUsers
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_newproto_fruitcart_proto_init() }
func file_newproto_fruitcart_proto_init() {
	if File_newproto_fruitcart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_newproto_fruitcart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalCartAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newproto_fruitcart_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_newproto_fruitcart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newproto_fruitcart_proto_goTypes,
		DependencyIndexes: file_newproto_fruitcart_proto_depIdxs,
		MessageInfos:      file_newproto_fruitcart_proto_msgTypes,
	}.Build()
	File_newproto_fruitcart_proto = out.File
	file_newproto_fruitcart_proto_rawDesc = nil
	file_newproto_fruitcart_proto_goTypes = nil
	file_newproto_fruitcart_proto_depIdxs = nil
}
